# 1. Numpy : it is shortcut for numerical python and used for mathematical operations.
# 2. Numpy is for dealing with metrices which is used in ML.
# 3. The dataset is a matrix whether it is tabular data, image represented in matrix and so on.

## 1.1. Creating array
### The array items must be the same type.

In [1]:
import numpy as np

# array from 2d list
x = np.array(
    [[1, 6, 3],
    [7, 4, 1]]
    )

print(x)

[[1 6 3]
 [7 4 1]]


## x is an object from the numpy module
## shape is an attribute in numpy

In [2]:
print('shape =', x.shape)

shape = (2, 3)


In [3]:
print(x.dtype)

int64


In [4]:
# 1d array
x2 = np.array([10, 20, 30])
print(x2)

[10 20 30]


In [5]:
print('shape =', x2.shape)

shape = (3,)


In [6]:
print(x2.dtype)

int64


### Array of zeros

In [7]:
# array of zeros 3x2
y = np.zeros((10, 20))

print(y)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### Array of ones

In [8]:
# array of ones 2x3
z = np.ones((2, 3))

print(z)

[[1. 1. 1.]
 [1. 1. 1.]]


### Identity matrix: using eye function
### it is a square matrix where the diagonal has ones and the other values are zeros.
### It takes only one parameter --> 4 means 4*4

In [9]:
# identity matrix (I) of size 4
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### arange such as range.

In [10]:
# array of numbers in range 0-9
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
# array of numbers in range 20-48 step 2
x = np.arange(20, 50, 2)
print(x)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


## 1.2. Indexing : [row, column]

In [12]:
x = np.array([
    [10, 20, 30, 40],
    [1, 2, 4, 5],
    [2, 2, 0, 1]
])

# a single element
print(x[0, 1])

20


### printing a whole row

In [13]:
print(x[1, :])

[1 2 4 5]


### printing the whole column

In [14]:
print(x[:, 0])

[10  1  2]


### sub matrix

In [15]:
print(x[0:2, 1:3])

[[20 30]
 [ 2  4]]


### Mask

In [16]:
x = np.array([
    [10, 20, 30, 40],
    [1, 2, 4, 5],
    [2, 2, 0, 1]
])

# create a boolean mask of elements > 20
mask = (x > 20)
print(mask)

[[False False  True  True]
 [False False False False]
 [False False False False]]


In [17]:
# print elements where mask = True
print(x[mask])

[30 40]


In [18]:
# same as previous but in one step
print(x[x > 20])

[30 40]


### copy function in numpy: the modifications in the new array doesn't affect the original one.

In [19]:
x1 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

x2 = x1[0, :].copy()

print(x1)
print()

print(x2)
print()
print()

## modification in the second array
x2[1] = 200

print(x1)
print()
print(x2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[1 2 3 4]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[  1 200   3   4]


### View function : any modification in the new array affects the original one.
### while it views the original one, it points at the original in the memory.

In [20]:
x1 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

x2 = x1[0, :].view()

print(x1)
print(x2)

x2[1] = 200

print(x1)
print()
print(x2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[[  1 200   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

[  1 200   3   4]


## 1.3. Transpose and reshape

In [21]:
x = np.array([
    [10, 20, 30, 40],
    [1,  2,  4,  5],
    [2,  2,  0,  1]
])

print(x.T)

[[10  1  2]
 [20  2  2]
 [30  4  0]
 [40  5  1]]


In [22]:
print(x.shape)

(3, 4)


### reshape function: to reshape the array but the multiplication of the old one is the same as the new reshaped array.
### 3 multiply 4 --> 1 multiply 12

In [23]:
print(x.reshape(1, 12))

[[10 20 30 40  1  2  4  5  2  2  0  1]]


In [24]:
x.reshape(2,6)

array([[10, 20, 30, 40,  1,  2],
       [ 4,  5,  2,  2,  0,  1]])

In [25]:
print(x.reshape(12,))   # one dimention , vector

[10 20 30 40  1  2  4  5  2  2  0  1]


In [40]:
x = np.array([
    [10, 20, 30, 40],
    [1,  2,  4,  5],
    [2,  2,  0,  1]
])

# getting first column and reshaping it to 3x1
print(x[:, 0])

[10  1  2]


In [42]:
print(x[:, 0].reshape(3, 1))

[[10]
 [ 1]
 [ 2]]


### reshape (-1,1) is used when the dimension of the array is unknown and you want to reshape it to be one vector.


In [27]:
print(x[:, 0].reshape(-1, 1))

[[10]
 [ 1]
 [ 2]]


In [28]:
# same as previous (if you use -1, numpy will calculate
#                   this dimension for you)
print(x[:, 0].reshape(1, -1))

[[10  1  2]]


## 1.4. Maths

### 1.4.1. Element-wise operations
### Addition, subtraction, multlpication and division matrices must have the same shape.

In [29]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

y = np.array([
    [2, 5, 1],
    [4, 2, 3]
])


# addition
z = x + y
print(z)
print()

[[3 7 4]
 [8 7 9]]



In [30]:
# subtraction
z = x - y
print(z)
print()

[[-1 -3  2]
 [ 0  3  3]]



### This is element wise multiplication --> it means multiply each element in the first matrix with the corresponding one in the second matrix.
### This type of multplication is different from the dot product.

In [31]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

y = np.array([
    [2, 5, 1],
    [4, 2, 3]
])


z = x * y
print(z)
print()

[[ 2 10  3]
 [16 10 18]]



In [32]:
# element-wise division
z = x / y
print(z)
print()

[[0.5 0.4 3. ]
 [1.  2.5 2. ]]



### 1.4.2. Matrix multiplication

In [33]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

y = np.array([
    [2, 5, 1, 1],
    [4, 2, 3, 2],
    [1, 2, 2, 5]
])

print('x.shape =', x.shape)
print('y.shape =', y.shape)
print()

# matrix multiplication , dot matrix multiplication
z = np.dot(x, y)
print(z)
print()
print('z.shape =', z.shape)

x.shape = (2, 3)
y.shape = (3, 4)

[[13 15 13 20]
 [34 42 31 44]]

z.shape = (2, 4)


### 1.4.3. sum

In [34]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# sum all alements
print(x.sum())

21


In [35]:
x.shape

(2, 3)

### summation of the columns
### axis = 0 means work on the columns
### keepdims means keep the same original dimension

In [36]:
res= x.sum(axis=0,keepdims=True)
print(res)
print(res.shape)

[[5 7 9]]
(1, 3)


### summation of the rows
### axis = 1

In [37]:
# sum each row
print(x.sum(axis=1, keepdims=True))

[[ 6]
 [15]]


### 1.4.4. exponent and log functions
#### exponent for each element in the matrix using np.exp
### the usual exponent works only on one number

In [38]:
y = np.exp(x)
print(y)

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [39]:
# calculate natural logarithm log(x) for each element
# [we can also use log2(x) and log10(x) for base 2 and base 10]
y = np.log10(x)
print(y)

[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]


See also:
- np.sqrt(x)
- np.abs(x)
- np.sin(x)
- np.cos(x)
- np.tan(x)

...